### ISSUE TITLE
upgrade.php fails with php 8.1

### ISSUE THREAD

**Issue by DagNygren** [fudforum/FUDforum#27]
Seems like some more argument checking in PHP 8.1 has been introduced and found a bug in line 369 of upgrade.php.

The line is: @chmod($file, 0644); which will try to chmod the contents of the file, not the file itself. Should it be @chmod($path, 0644); instead ?

I just commented out the line and the upgrade completed.
But there are some more small details with 8.1 also. In user manager I will on some pages see the note: 

`( ! ) Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /home/httpd/fraudforum/phpfiles/adm/admuser.php on line 316 `

And I guess there are others I haven't found yet...

**Comment by naudefj** [comment]
Fixed as per https://github.com/fudforum/FUDforum/compare/a439e73c0dc1...c1f6ecc0551d
Thank you for reporting these issues.

Regards.
Frank
