### ISSUE TITLE
User Manager - Delete All messages by this user

### ISSUE THREAD

**Issue by GaryM0101** [fudforum/FUDforum#29]
When trying to delete all messages for a users I get a "Not Found The requested URL was not found on this server." Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

System Information:
FUDforum version: | 3.1.2
PHP version: | 7.4.30
PHP built on: | Linux dooly 5.4.32-grsec-grsec-plus+ #1 SMP Sat Apr 18 03:13:45 UTC 2020 x86_64
Database type: | mysql (mysqli)
Database version: | 8.0.28-0ubuntu0.20.04.3
Web server: | Apache
Web Server load: | 4.05
Web server to PHP interface: | cgi-fcgi

**Comment by naudefj** [comment]
Fixed @ https://github.com/fudforum/FUDforum/commit/f9fab328aef48e9935cdd26c1661af32671b7a0b
