### ISSUE TITLE
PHP8.1 Deprecated error

### ISSUE THREAD

**Issue by JennekeGruen** [fudforum/FUDforum#30]
Admin panel action log mentions:
Deprecated: htmlentities(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxx/vintagegruen.org/xxx/adm/admlog.php on line 102

Effect: Replying to a topic gives a white screen. Message is posted.

PHP 8.1 is the running version (our host recommends it). Downgrading to PHP 8.0 seems to solve the issue, but not the preferred solution.

Does someone have a fix?

**Comment by naudefj** [comment]
Please try the following. 

Find this line in the file admlog.php - 
   $obj->logaction = htmlentities($obj->logaction);
and replace it with -
   $obj->logaction = htmlentities($obj->logaction ?? '');

**Comment by naudefj** [comment]
I've upgraded one of my sites to PHP 8.2 and fixed most (if not all) of the compatibility errors.
Please try again with the latest code and let me know if you experience any other issues.

**Comment by JennekeGruen** [comment]
Updated the forum to 3.1.3 today. Als also PHP to 8.2. White screen issue seems to be fixed!

But… getting a deprecated error under the category manager:
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxx/adm/admcat.php on line 265

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /home/xxx/adm/admcat.php on line 267

**Comment by naudefj** [comment]
Fixed @ https://github.com/fudforum/FUDforum/commit/c1626d795b3c85a781803dfad7f630f7aa6da00c
