### ISSUE TITLE
Email registration confirmation fails

### ISSUE THREAD

**Issue by JennekeGruen** [fudforum/FUDforum#32]
When a new member gets an Email registration confirmation email, the confirmation/activate account link gives an error. 
![91E62B68-2D3D-4BD7-84B3-D9AF5DB8C2A6](https://user-images.githubusercontent.com/103288970/236917278-ffcfd218-587b-450d-970c-d5b090749f14.jpeg)

Nothing in the error log.

A new user cant activate his account, after sending us an email, we can toggle email confirmation manually in the admin panel (workaround).

Not sure if related. Under datadir is the user table filled with the members. If I select it, it shoots the preg_match and htmlspecialchar deprecated error.

**Comment by JennekeGruen** [comment]
English error 😅:
![DC9A9907-90F4-46E4-9229-B2DCDBC749FD](https://user-images.githubusercontent.com/103288970/236918039-ecdb2dab-c2e2-4dae-8f1f-b02a97f31707.jpeg)

**Comment by JennekeGruen** [comment]
Thanx. An new version would be nice. 😊

To apply those fixes we cant use the admin panel (edit file in src) option because it shoots a 500 internal server error. We have to download, change, upload and chmod the file…

**Comment by JennekeGruen** [comment]
Ok. This might be a stupid question, but I just dont fully understand how patches work.

for example, fix c1626d7 (deprec errors) was in a .php file. Under the webdir. We managed to change the file and it worked like a charm.

But this change b18da7a (user confirmation) was in a php.t file. Under the fudforum scr folder. Changing that didnt solve the issue.

question is:
- Should we recompile, build themes or whatever to get fixes in that part working
- Or can it only be fixed with a new version (update)
- Another option is that the fix isnt fixing the issue… 😢

**Comment by naudefj** [comment]
The first option should work - just recompile the theme.
Option two can also work, but is not ready yet.
I hope it's not option 3!!!

**Comment by JennekeGruen** [comment]
🥳 option 1 did the trick.
