### ISSUE TITLE
FUDforum website down

### ISSUE THREAD

**Issue by Knezzen** [fudforum/FUDforum#39]
Hi!

I can't seem to connect to fudforum.org. Is the forum down?

**Comment by jethro-swan** [comment]
It's still inaccessible. No response to ping **fudforum.org** (216.235.13.26).

**Comment by jethro-swan** [comment]
Even before this there was a problem. Even when the site was up, my attempts to register a few weeks earlier failed repeatedly and no-one responded to my request for help. Is anyone monitoring this?

**Comment by southern-computer-geek** [comment]
@naudefj

**Comment by tommyhoz** [comment]
Still down , no luck

**Comment by jethro-swan** [comment]
It's back ... but still no explanation.

**Comment by naudefj** [comment]
The fudforum website belongs to the original author and is not under my control.
Luckily, everything you need to run the software is available here on Github.

**Comment by jethro-swan** [comment]
> The fudforum website belongs to the original author and is not under my control. Luckily, everything you need to run the software is available here on Github.

That's very reassuring. Thanks.

However, it hasn't been clear to me who's in charge of what - so this new information is helpful.
